/**
 * AUTO-GENERATED by scripts/compute-team-accents.mjs — do not hand-edit.
 * Edit SOURCE_TEAM_COLORS in that script and run `npm run compute:team-accents`.
 *
 * primary/secondary: community-sourced livery reference, not pulled from
 * official F1 broadcast graphics — an approximation worth a real
 * verification pass later, not a fact the way a stat would be.
 *
 * uiAccent: deterministically derived from primary/secondary (CIE76 collision
 * check against every other team's accent, in stable order) — never
 * hand-picked, except where a per-team comment says "PINNED" (a documented,
 * deliberate override, not an algorithm output). Use uiAccent anywhere
 * multiple teams must be simultaneously distinguishable in a list (e.g. the
 * standings-row accent bar, which also always renders with a 1px Brushed
 * Steel outline — see StandingsTable — so background contrast is handled
 * structurally and isn't gated here). Team profile pages / hero sections
 * should use primary/secondary instead, since showing the real livery
 * matters more there than list-differentiation.
 */
export interface TeamColor {
  primary: string;
  secondary: string;
  uiAccent: string;
}

export const TEAM_COLORS: Record<string, TeamColor> = {
  mclaren: { primary: "#FF8000", secondary: "#000000", uiAccent: "#FF8000" },
  ferrari: { primary: "#E80020", secondary: "#FFFFFF", uiAccent: "#E80020" },
  red_bull: { primary: "#3671C6", secondary: "#FFCC00", uiAccent: "#3671C6" },
  // PINNED — Deliberate pin, not an algorithmic fallback: Mercedes and Cadillac both have black as their true primary. Letting the algorithm resolve that competition would only relocate the collision to whichever team loses the stable-order tiebreak — so Mercedes is pinned to its other real brand color (teal) instead, freeing black for Cadillac and letting both teams render distinctly.
  mercedes: { primary: "#000000", secondary: "#27F4D2", uiAccent: "#27F4D2" },
  aston_martin: { primary: "#00665E", secondary: "#CEDC00", uiAccent: "#00665E" },
  alpine: { primary: "#FF87BC", secondary: "#0090FF", uiAccent: "#FF87BC" },
  williams: { primary: "#64C4FF", secondary: "#041E42", uiAccent: "#64C4FF" },
  rb: { primary: "#FFFFFF", secondary: "#6692FF", uiAccent: "#FFFFFF" },
  // Accepted collision, not a bug: white (RB) and red (Ferrari) — Haas's only two real colors — are both already claimed by earlier teams in stable order. There's no third color to invent without breaking the primary-or-secondary-only rule. The row's team-name text is the real disambiguator here; the accent bar is decorative reinforcement only.
  haas: { primary: "#FFFFFF", secondary: "#E6002B", uiAccent: "#FFFFFF" },
  audi: { primary: "#C8CED4", secondary: "#F50537", uiAccent: "#C8CED4" },
  cadillac: { primary: "#FFFFFF", secondary: "#000000", uiAccent: "#000000" },
};

const FALLBACK_COLOR: TeamColor = {
  primary: "#8A8F94",
  secondary: "#2A2D30",
  uiAccent: "#8A8F94",
}; // Brushed Steel / Asphalt — unknown constructorId

export function getTeamColors(constructorId: string): TeamColor {
  return TEAM_COLORS[constructorId] ?? FALLBACK_COLOR;
}

/** Real livery primary — for team profile pages / hero sections, not lists. */
export function getTeamColor(constructorId: string): string {
  return getTeamColors(constructorId).primary;
}

/** Collision-safe accent — for standings rows and anywhere teams must read as distinct in a list. */
export function getTeamUiAccent(constructorId: string): string {
  return getTeamColors(constructorId).uiAccent;
}
